
import { Inter } from "next/font/google";
//import "./globals.css";
import "../styles/scss/bootstrap.scss";
import "../styles/css/bootstrap.min.css";
import "../styles/css/style.css";

import Script from 'next/script';
// import "../js/scripts.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zambezi Cancer Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* <!-- Google Web Fonts --> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap" rel="stylesheet" />


        {/* <!-- Icon Font Stylesheet --> */}
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

        {/* <!-- Libraries Stylesheet --> */}
        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet"></link>
      </head>
      <body className={inter.className}>
        {children}

        {/*-- JavaScript Libraries */}
        <Script async src="https://code.jquery.com/jquery-3.4.1.min.js" strategy="beforeInteractive" />
        <Script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" />
        <Script async src="lib/wow/wow.min.js" strategy="beforeInteractive" />
        <Script async src="lib/easing/easing.min.js" strategy="beforeInteractive" />
        <Script async src="lib/waypoints/waypoints.min.js" strategy="beforeInteractive" />
        <Script async src="lib/owlcarousel/owl.carousel.min.js" strategy="beforeInteractive" />
        <Script async src="lib/parallax/parallax.min.js" strategy="beforeInteractive" />

        {/* Template Javascript */}
        <Script async src="js/main.js" />
        <Script async src="js/scripts.js" />
      </body>
    </html>
  );
}
