import { Inter } from "next/font/google";
//import "./globals.css";
import "../styles/style.css";
import "../styles/bootstrap.min.css";
// import "../js/scripts.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zambezi Cancer Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script
          async
          src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js'
        ></script>
        {/* theme js */}
        <script async src='js/scripts.js'></script>
        {/* startbootstrap forms */}
        <script
          async
          src='https://cdn.startbootstrap.com/sb-forms-latest.js'
        ></script>
      </body>
    </html>
  );
}
