import { Inter } from "next/font/google";
//import "./globals.css";
import "../styles/style.css";
import "../styles/bootstrap.min.css";
// import "../js/scripts.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zambezi Cancer Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/*-- JavaScript Libraries */}
        <script async src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script async  src="lib/wow/wow.min.js"></script>
        <script async  src="lib/easing/easing.min.js"></script>
        <script async  src="lib/waypoints/waypoints.min.js"></script>
        <script async  src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script async  src="lib/parallax/parallax.min.js"></script>

        {/* Template Javascript */}
        <script async  src="js/main.js"></script>
      </body>
    </html>
  );
}
